### ISSUE TITLE
How do I connect the dump to a service?

### ISSUE THREAD

**Issue by tomaswitek** [hello-aurora/railway-volume-dump#2]
Hey thx a lot for your template. I need exactly something like this.
I am afraid I do not get how to connect this to a volume from a different service. 
In my case the directus service. I want to dump the upload volume which is attached to a different service
Can you please help?
Thx

![Snímek obrazovky 2024-12-05 v 8 26 02](https://github.com/user-attachments/assets/73df00e0-8467-4f9d-a40b-b48506d5dd29)

**Comment by tomaswitek** [comment]
And even why I delete a service and reattach the existing volume to the new service I get errrors:
![Snímek obrazovky 2024-12-05 v 8 33 04](https://github.com/user-attachments/assets/45ca6276-94fb-4240-9238-c9aef87b95db)
![Snímek obrazovky 2024-12-05 v 8 34 21](https://github.com/user-attachments/assets/7ba593f4-f0b1-4108-a92f-1b3791f8e2d9)

**Comment by jeremybarbet** [comment]
Hey there!

Regarding your first comment, it's actually a good point that I didn't added to the notes of the readme. You need to "disconnect volume" from the service the volume is attached to (in this case "directus") and then "mount" it to the "railway-volume-dump" service.

At the moment Railway doesn't provide a way to attach a volume to multiple services, meaning it will cause downtime to your service. Just be aware of that if this is a production service.

Regarding your second screenshot, are you sure you have data in your volume? You can check the "deploy logs" in the service settings from "railway-volume-dump" it should tell you how many files it processed. Also, I don't have access to the database backup feature, so I'm not sure if that's related to it.

Cheers

**Comment by tomaswitek** [comment]
Hey @jeremybarbet 
Yep I thought so I have to disconnect and reconnect it. That worked, however I still get the same error. And yes I am sure there are data in the volume. You can even see it on the picture that the volume is not empty. There is also nothing in the deploy logs:
![Snímek obrazovky 2024-12-05 v 14 43 34](https://github.com/user-attachments/assets/01c648c5-1727-484c-8434-1c5f44946927)

**Comment by tomaswitek** [comment]
<img width="1010" alt="Snímek obrazovky 2024-12-05 v 14 45 02" src="https://github.com/user-attachments/assets/914cfcbc-13e8-4eef-ad9a-349890445e91">

**Comment by jeremybarbet** [comment]
Alright, I could replicate the error if not passing the protocol (`https`). By any chance, did you just copy the generated domain?

**Comment by fubipod** [comment]
Sorry @jeremybarbet I was offline for a while. But yes you were right. It works like a charm now. Thx for the great work you've done with this template. It is really something what's missing in Railway. Thx also for extending the documentation now. ❤️
